### ISSUE TITLE
[Suggestion]: connecting diagonally to opaque blocks?

### ISSUE THREAD

**Issue by Internetter2002** [Fuzss/diagonalwindows#15]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

v8.1.4

### Suggestion (Required)

Glass panes already connect between blocks in the cardinal directions. I feel like it would be far more useful for them to repeat that behaviour diagonally too than to just leave that gap. It would allow completely diagonal windows to run between blocks circumventing the need to "bend" them at the edges just so they connect without gaps.

![2024-09-07_00 37 57](https://github.com/user-attachments/assets/99a1c963-5825-4efc-9c1f-2a5e1ce4c2f2)

**Comment by Fuzss** [comment]
That’s technically not possible unfortunately.
