### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ciellix** [Fuzss/diagonalwindows#16]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

v21.1.

### Minimal Setup (Required)

No

### Notes (Required)

same issue as here https://github.com/Fuzss/diagonalfences/issues/31

### latest.log (Required)

https://mclo.gs/JPW8YHO

**Comment by Fuzss** [comment]
https://github.com/Fuzss/diagonalfences/issues/31#issuecomment-2485191874
