### ISSUE TITLE
[Bug]: Stained Glass Panes connect wrongly in generated structures

### ISSUE THREAD

**Issue by MageInBlack** [Fuzss/diagonalwindows#2]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

Currently some structures that spawn from structure mods (currently was observed in villages) spawn with stained glass panes connected diagonally to some nonexistent blocks. Doesn't apply to the regular glass panes as they are acting as supposed to. I am not sure if it applies to bars as i haven't seen any bars in structures behaving like that.
Edit: if you break and place them back in the ones placed connect as they are supposed to.
The panes can be seen at:
https://i.imgur.com/wc0svOR.png
https://i.imgur.com/vDlizlB.png
https://i.imgur.com/WKekYNg.png

**Comment by Fuzss** [comment]
Thanks, fixed in latest version.
