### ISSUE TITLE
[Bug]: incorrect block returned in packets

### ISSUE THREAD

**Issue by vgrynch** [Fuzss/diagonalwindows#3]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.2-1.19.2-Forge

### Notes (Required)

I'm using a large modpack (200+ mods), running on the ArcLight 1.19.2 server connected through the Velocity proxy.

After adding this mod, certain blocks that have multiple states start to look wrong when interacting with them. See the screenshot as an example. It looks like the server sends an object ID that is different from what is on the client. As a result, visually, a different block is rendered after the interaction. When teleporting away and then teleporting back, so the chunk is reloaded, the item returns to normal displaying.
No errors or warnings in logs are observed related to this.

This behavior is tracked to this mod by using the "binary search" algorithm (removing part of the mods and checking if the behavior reproduces).
Also, I have tried to connect directly to the server without the proxy, remove any mods responsible for rendering optimizations or tweaks, and remove all mods related to network optimizations/fixes.

Blocks or items that are displayed wrongly vary. Sometimes it's a custom chest, sometimes it's a cabinet from furniture mod, sometimes it's tree leaves or top of the growing kelp, all are from different mods.

Testing scenario when it reproduces in a reliable way:
I used 2 connectors from "Create: Crafts & Additions" mod and trying to connect them with wire.
Screens:

before:
![image](https://github.com/Fuzss/diagonalwindows/assets/46818018/950006d1-2011-4be5-a86c-bc40e51550c0)

after placing wire between connectors:
![image](https://github.com/Fuzss/diagonalwindows/assets/46818018/afc538fb-2d7c-44b3-9aaa-5864931084e0)

after teleporting away and returning back:
![image](https://github.com/Fuzss/diagonalwindows/assets/46818018/e0cd5372-33a8-45ca-9c5c-0a2adb8426a0)

Please, fix it.

**Comment by vgrynch** [comment]
I also wonder, why this behavior is different from the Diagonal Fences mod that I'm also using. No issues with Diagonal fences were observer after 2 weeks of using. Added Diagonal Windows yesterday, and this issue...

**Comment by Fuzss** [comment]
Diagonal Fences needs to be installed in your server, too. This issue arises when it’s absent.

**Comment by vgrynch** [comment]
It is installed, and versions match.

**Comment by vgrynch** [comment]
This bug most likely is related to the Minecraft issue in 1.19.2:
https://bugs.mojang.com/browse/MC-258163
There is a mod - https://www.curseforge.com/minecraft/mc-mods/block-limit-fix
It fixes this bug.
After adding the above mod, the problem seems to have gone. I will need to do more testing though and will let you know if the issue may be closed.

**Comment by vgrynch** [comment]
After further testing, it appears that the problem did not go away completely. It appears, but now with a higher number of mods (270+) However, still, there is a suspicion it is related to the large number of states in the large modpack. If you want, we can close this issue as I will track all this further in another mod issue.

**Comment by vgrynch** [comment]
The issue, indeed, is related to https://bugs.mojang.com/browse/MC-258163. The last problem was that the Block Limit Fix mod was not built properly, so it simply did not work under 1.19.2. I re-built it myself under 1.19.2 version and it worked well and fixed this mod behavior, Create mod, and a few others.

Closing.
