### ISSUE TITLE
[Bug]: Log spam

### ISSUE THREAD

**Issue by Ultimushadow** [Fuzss/diagonalwindows#5]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

I was testing a pack with this mod, and with Chipped. This mod would give a warning every time the game was loaded about incompatible window panes - this was very annoying, and I was already planning on writing out a suggestion. However, when testing Every Compat, this problem got magnified to a legitimate resource issue. For _every possible orientation_ of an incompatible glass pane which included a diagonal set to true, the game logged an error message that complained about missing textures. I don't think this mod is directly causing the error message but even without Every Compat, I wanted to suggest a way to turn the logs off. I've launched the game a hundred times, I know that glass pane is incompatible! My poor logs are so cluttered with useless information like this that it makes it hard to get to things that actually matter. 

I would like to know who else this issue report needs to be brought to, Every Compat or Chipped. I assume the former? But I'm not really sure

### latest.log (Optional)

I literally can't upload the log from the Every Compat because it's too big

**Comment by Fuzss** [comment]
Thanks for reporting! I'll make sure every incompatible block is only reported once independently of block states in the next version.

Connections still won't be visible for both mods if they were logged as incompatible, I'll look into that in a separate issue.

**Comment by Fuzss** [comment]
Resolved in v8.1.0.
