### ISSUE TITLE
[Crash]: Incompatibility with Galosphere

### ISSUE THREAD

**Issue by Mysterious-Wrangler** [Fuzss/diagonalwindows#7]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.0

### Notes (Required)

When i installed this mod the game crashed and said this:
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'galosphere'!"
I have provided the crash log and am using fabric 0.14.23

### Crash Report (Required)

https://gist.github.com/Mysterious-Wrangler/2a78ab1abab147ac17f40fe4b4368ec3

**Comment by Fuzss** [comment]
Fixed in latest version.
